// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ByVpfmPwsPOMrqz7cz5PwjRzqsuqMyo',
    appId: '1:685635931124:web:be38b1cb70b0d40a72c7a1',
    messagingSenderId: '685635931124',
    projectId: 'examen-408d3',
    authDomain: 'examen-408d3.firebaseapp.com',
    storageBucket: 'examen-408d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhwIbO4P1jT61bLKrjHJ3A_LGWyng8GKk',
    appId: '1:685635931124:android:98dc4ca7acb360f272c7a1',
    messagingSenderId: '685635931124',
    projectId: 'examen-408d3',
    storageBucket: 'examen-408d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVPepy7rJe3K8YTSvYNIMIqYGj-bd5las',
    appId: '1:685635931124:ios:1250f479dfa638ef72c7a1',
    messagingSenderId: '685635931124',
    projectId: 'examen-408d3',
    storageBucket: 'examen-408d3.firebasestorage.app',
    iosBundleId: 'com.example.examenOscarBarrios',
  );
}
